### ISSUE TITLE
Can versions be allowed to go backwards?

### ISSUE THREAD

**Issue by ryandawsonuk** [jenkins-x/jx-release-version#21]
Our example docker images are being generated starting with 7 because the versions of our tags are incrementing from 7.0.x. But this is confusing as our pom says 1.0.0:

https://github.com/Activiti/example-runtime-bundle/commit/ae6ec8f0a7d525e39e41113d8e3f210746550a7f#diff-600376dffeb79835ede4a0b285078036

The reason seems to be that in the past our pom.xml did say 7.0.0 and we then moved our version number down. However we can't go back to 1.0.x as `jx-release-version` [won't let us go backwards](https://github.com/jenkins-x/jx-release-version/blob/master/main.go#L274). 

What can we do on this? Would a non-semantic version be possible? The trouble is [we can't really move our versions forwards as they've already gone further forwards than we should've let them go](https://github.com/Activiti/Activiti/issues/2485).

**Comment by salaboy** [comment]
- Create spring boot QuickStart
  - develop branch -> Pom -> 1.1.0-SNAPSHOT
  - 1.0.x branch -> Pom ->  1.0.0-SNAPSHOT

When building the two pipelines 
we should get the right release number for both.
