### ISSUE TITLE
Support for cmake

### ISSUE THREAD

**Issue by DJViking** [jenkins-x/jx-release-version#27]
Support for cmake by reading the version from CMakeLists.txt

    project(project VERSION 2.1 LANGUAGES CXX)

RegEx for getting the version:

    project\\s*\\(([^\\s]+)\\s+VERSION\\s+([.\\d]+).*\\)

This tool worked on a cmake project, but only master. For any release branch it output 0.0.1, even if I used --same-release. If I create a Makefile here with the version in CMakeLists.txt it works.

**Comment by DJViking** [comment]
I made an implementation for reading CMakeLists.txt, but the regex did not work to match with 1.2.0-SNAPSHOT, just 1.2.0

**Comment by DJViking** [comment]
feature merged to master

**Comment by galaxyNeha** [comment]
I am getting and error, 

CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
--
  |   |   |   | CMake 3.14 or higher is required.  You are running version 3.7.2

What should I do about it?

**Comment by vbehar** [comment]
Hi,
which command are you running? your error seems like a cmake error, but the only thing this project does is reading the `CMakeLists.txt` file - it doesn't run cmake.
