### ISSUE TITLE
Error getting version of maven project

### ISSUE THREAD

**Issue by DJViking** [jenkins-x/jx-release-version#29]
Running this tool on any release branch, that is below master.
/jx-release-version-linux 
failed to get new version strconv.ParseInt: parsing "51.2": invalid syntax

If I use --same-release, it works on this branch.

Running this tool on master branch, which does not have any release tags
./jx-release-version-linux 
failed to get new version error fetching tags: exit status 1

**Comment by dodwyer** [comment]
I believe this is because you are using a non-semver version. 
I had this issue and changed my versions from 1.0.0.0 to 1.0.0 and it worked.

**Comment by DJViking** [comment]
The version on this project is X.Y.Z-SNAPSHOT, and is in accordance to SamVer.

**Comment by dodwyer** [comment]
What's the version in your pom.xml file?

**Comment by DJViking** [comment]
origin/master > 3.1.0-SNAPSHOT

    ./jx-release-version-linux
    failed to get new version strconv.ParseInt: parsing "51.2": invalid syntax

But with same-release it works:

    ./jx-release-version-linux --same-release
    3.1.0

If I create a git tag for master v3.1.0, then I do not get the error without using --same-release

On the release branch, which does have many git release tags.
origin/ReleaseB > 2.0.30-SNAPSHOT
Got same problem as with master, and it got away If I create a git release tag for the master version.

**Comment by hsmiranda** [comment]
> I believe this is because you are using a non-semver version.
> I had this issue and changed my versions from 1.0.0.0 to 1.0.0 and it worked.

it worked, thanks!
