### ISSUE TITLE
GIT_ASKPASS

### ISSUE THREAD

**Issue by imod** [jenkins-x/jx-release-version#6]
this is really an awesome tool!
We use it outside of jenkins-x in a normal jenkins installation where we install it as a 'custom tool'. But now we started to see an issue on some of our builds, where it fails to resolve the next version unfortunate its a bit hard to debug the issue. 

All I currently get is:
`failed to get new version error fetching tags: %vexit status 128`

My guess is that it does not work for some git authentication issues. Therefore I tried to call it with `GIT_ASKPASS` (using this lib: https://github.com/imod/jenkins-git-askpass-pipeline-lib) - one point to mention might also be that we use the bitbucket "multibranch plugin", there only https is available to fetch from the git remote.

@rawlingsj it would be very very cool, if you could help my out here :)

**Comment by rawlingsj** [comment]
hi @imod sorry - I'd missed the issue notification for this repo.  I'm not too sure what can be going on ATM as all `jx-release-version` is doing is deferring to the git cli for that call https://github.com/jenkins-x/jx-release-version/blob/master/main.go#L166-L170

I wonder if in your build pipeline you can add an input or sleep before this step, then exec / ssh into the container or VM and run the command `git fetch --tags -v` to see if it errors?

**Comment by imod** [comment]
hey @rawlingsj many thanks!

I did a short test with `git fetch --tags -v` and added the following two lines to my script:

```
      script.gitAskPass(gitCredentialsId, "git fetch --tags -v")
      script.sh "git fetch --tags -v"
```

both lines execute the exact same git command, but the first does the call by setting `GIT_ASKPASS` first, so the two lines get executed like this:

```
GIT_ASKPASS=/path/to/ask/pass/script git fetch --tags -v
git fetch --tags -v
```

as a result, the first call to fetch the tags works fine, but the second fails with this error:

```
fatal: could not read Username for 'https://bitbucket.org': No such device or address
```

This is the usual error when git does not now which user/password to us - so, the exact information which is provided with `GIT_ASKPASS` on the first line.

Trying to resolve this, I also tried to do this:

```
GIT_ASKPASS=/path/to/ask/pass/script jx-release-version
```

but this fails with the exact same error and I think the reason is very simple: `jx-release-version` calls a new process and there `GIT_ASKPASS` is not set https://github.com/jenkins-x/jx-release-version/blob/master/main.go#L166-L170 

Do you see any way this could be improved?

**Comment by rawlingsj** [comment]
does 
```
script.gitAskPass(gitCredentialsId, "jx-release-version")
```
or
```
GIT_ASKPASS=/path/to/ask/pass/script jx-release-version
``` 
fail too?

I'm surprised that env vars are not passed on TBH.

Are you suggesting we add something like this...?
```
cmd := exec.Command("git", "fetch", "--tags", "-v")
cmd.Env = append(cmd.Env, "GIT_ASKPASS="+os.Getenv("GIT_ASKPASS"))
err := cmd.Run()
```

**Comment by imod** [comment]
exactly - I tested it and it does not seem to work :(
yeah, adding it that way should probably fix the issue ...although I'm not a gopher :)

**Comment by imod** [comment]
I think the problem is not bitbucket, but using git via HTTP/S

**Comment by rawlingsj** [comment]
I was more saying so I can recreate the issue and test options against.  FWIW we use https://git-scm.com/docs/git-credential-store and mount the git creds as a secret into a kubernetes pod.  

I'll quickly add that `cmd.Env = append(cmd.Env, "GIT_ASKPASS="+os.Getenv("GIT_ASKPASS")) ` now and trigger a release  to see if that works as a start.

**Comment by rawlingsj** [comment]
1.0.11 has that update if you wanna try it out https://github.com/jenkins-x/jx-release-version/releases/tag/v1.0.11

**Comment by imod** [comment]
wow - very cool!
the only problem now is, that the linux build is missing on: https://github.com/jenkins-x/jx-release-version/releases/tag/v1.0.11

**Comment by imod** [comment]
@rawlingsj sorry, I don't wanna be a pain - but would you be able to do an other release which also contains the linux binaries?

**Comment by rawlingsj** [comment]
I retriggered the release yesterday and the binaries are now there for the latest release https://github.com/jenkins-x/jx-release-version/releases/tag/v1.0.12

**Comment by imod** [comment]
@rawlingsj many thanks! I now tested it again, but unfortunate it still does not work and I don't know the reason :(


The important part of the script is this:
```
  def mvnReleaseMasterBranch(String workingDir, Closure doBeforeBuild = {}) {
    // doGitGlobalConfig()
    script.dir(workingDir){
      script.echo "start release..."
      // ensure we're not on a detached head
      script.sh "git checkout master"
      // so we can retrieve the version in later steps
      script.echo "try 1"
      script.gitAskPass(gitCredentialsId, "git fetch --tags -v")
      script.echo "try 2"
      script.gitAskPass(gitCredentialsId, "jx-release-version")
      script.echo "try 3"
      script.gitAskPass(gitCredentialsId, "echo \$(jx-release-version) > VERSION")
      script.echo "try 4"
      script.sh "cat VERSION"
      def vrs = script.readFile('VERSION').trim()
      script.sh "mvn versions:set -DnewVersion=${vrs}"
      script.sh "git add --all"
      script.sh "git commit -m 'release ${vrs}' --allow-empty" // if first release then no version update is performed
      script.sh "git tag -fa v${vrs} -m 'Release version ${vrs}'"
      script.gitAskPass(gitCredentialsId, "git push origin v${vrs}")
      doBeforeBuild()
      script.sh "mvn clean deploy"
      def model = script.readMavenPom(file: 'pom.xml')
      def releasedArtifact = "${model.groupId}:${model.artifactId}:${model.version}"
      script.echo "released: ${releasedArtifact}"
      return releasedArtifact;
    }
  }
```
as you can see in the following output, it only get to `try 2` and fails at this command: `script.gitAskPass(gitCredentialsId, "jx-release-version")`
```
Running in /scratch/jenkins/workspace/g_aaaaa.bbbbbb_master-EITEV75RYI5RW5EHGXXG2SWQDCHPBMS5PFFAHBB4BUG2NASC4UDA
[Pipeline] {
[Pipeline] echo
start release...
[Pipeline] sh
[g_aaaaa.bbbbbb_master-EITEV75RYI5RW5EHGXXG2SWQDCHPBMS5PFFAHBB4BUG2NASC4UDA] Running shell script
+ git checkout master
Switched to a new branch 'master'
Branch master set up to track remote branch master from origin.
[Pipeline] echo
try 1
[Pipeline] pwd
[Pipeline] libraryResource
[Pipeline] writeFile
[Pipeline] withCredentials
[Pipeline] {
[Pipeline] sh
[g_aaaaa.bbbbbb_master-EITEV75RYI5RW5EHGXXG2SWQDCHPBMS5PFFAHBB4BUG2NASC4UDA] Running shell script
+ chmod +x /scratch/jenkins/workspace/g_aaaaa.bbbbbb_master-EITEV75RYI5RW5EHGXXG2SWQDCHPBMS5PFFAHBB4BUG2NASC4UDA@tmp/9f4cb81f-d407-40d9-87ff-fabce439364f
+ GIT_ASKPASS=/scratch/jenkins/workspace/g_aaaaa.bbbbbb_master-EITEV75RYI5RW5EHGXXG2SWQDCHPBMS5PFFAHBB4BUG2NASC4UDA@tmp/9f4cb81f-d407-40d9-87ff-fabce439364f
+ git fetch --tags -v
calling askpass script
calling askpass script
POST git-upload-pack (gzip 1502 to 820 bytes)
From https://bitbucket.org/aaaaa/aaaaa.bbbbbb
 = [up to date]      master     -> origin/master
 * [new tag]         1.2        -> 1.2
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.12     -> 1.2.12
 * [new tag]         1.2.13     -> 1.2.13
 * [new tag]         1.2.14     -> 1.2.14
 * [new tag]         1.2.15     -> 1.2.15
 * [new tag]         1.2.16     -> 1.2.16
 * [new tag]         1.2.17     -> 1.2.17
 * [new tag]         1.2.18     -> 1.2.18
 * [new tag]         1.2.19     -> 1.2.19
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.20     -> 1.2.20
 * [new tag]         1.2.21     -> 1.2.21
 * [new tag]         1.2.22     -> 1.2.22
 * [new tag]         1.2.23     -> 1.2.23
 * [new tag]         1.2.24     -> 1.2.24
 * [new tag]         1.2.25     -> 1.2.25
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.2.7      -> 1.2.7
 * [new tag]         1.2.9      -> 1.2.9
 * [new tag]         my-hotfix  -> my-hotfix
 * [new tag]         v1.2.26    -> v1.2.26
 * [new tag]         v1.2.27    -> v1.2.27
 * [new tag]         v1.2.28    -> v1.2.28
 * [new tag]         v1.2.29    -> v1.2.29
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] echo
try 2
[Pipeline] pwd
[Pipeline] libraryResource
[Pipeline] writeFile
[Pipeline] withCredentials
[Pipeline] {
[Pipeline] sh
[g_aaaaa.bbbbbb_master-EITEV75RYI5RW5EHGXXG2SWQDCHPBMS5PFFAHBB4BUG2NASC4UDA] Running shell script
+ chmod +x /scratch/jenkins/workspace/g_aaaaa.bbbbbb_master-EITEV75RYI5RW5EHGXXG2SWQDCHPBMS5PFFAHBB4BUG2NASC4UDA@tmp/1164073b-8487-472f-8377-590ab1ba2cf7
+ GIT_ASKPASS=/scratch/jenkins/workspace/g_aaaaa.bbbbbb_master-EITEV75RYI5RW5EHGXXG2SWQDCHPBMS5PFFAHBB4BUG2NASC4UDA@tmp/1164073b-8487-472f-8377-590ab1ba2cf7
+ jx-release-version
failed to get new version error fetching tags: %vexit status 128
```
whether the `jx-release-version` does see the `GIT_ASKPASS` I don't know (maybe some debig output would help)

do you have any idea how we could go on with this?

just FYI: this is all running on DEV@Cloud (by Cloudbees)...

**Comment by imod** [comment]
@rawlingsj I created a small PR to print the environment when run in debug mode: https://github.com/jenkins-x/jx-release-version/pull/8 

I tested everything locally, but was not able to reproduce the problem I see on DEV@cloud. But I do see a difference between version v1.0.10 and v1.0.12. Now guess is that some other variables which are used inside the 'GIT_ASKPASS'-script (USERNAME/PASSWORD) are also not available. To prove this, I would like to see the exact env that is available to `jx-release-version`

**Comment by imod** [comment]
ok, I now have been some how able to proved the environment to be the problem (although I have no idea why this is the case on DEV@cloud only):

My `GIT_ASKPASS`-script, originally also contains environment variables:

```
#!/bin/sh
case "$1" in
Username*) echo $USERNAME ;;
Password*) echo $PASSWORD ;;
esac
```
These variables are provided by the jenkins pipeline step `withCredentials`. For all executions this works fine, but in this case the resolving of the env variables does not work when `jx-release-version` calls `GIT_ASKPASS=xxxx git fetch --tags -v`

But the whole thing works fine when I replace the variables inside the script before calling `jx-release-version`.

As I mention, I have no idea why this is the case :( 
One solution might be to explicitly set all environment variables for the spawned command again. 
something like this:

```
		cmd := exec.Command("git", "fetch", "--tags", "-v")
		for _, e := range os.Environ() {
			cmd.Env = append(cmd.Env, e)
		}		
		err = cmd.Run()
```

**Comment by imod** [comment]
thanks for merging #8 - the output now shows that all env variables are available... But it does only prove they are available in the caller environment, not that they are available to `git fetch --tags -v` :(

I know my suggestion in the last comment is very strange, but would you be open to have a try with it? If yes, then I do a PR.

**Comment by rawlingsj** [comment]
Sure though TBH it's probably a lot easier to install golang and hack / try things yourself...

If you install go https://golang.org/doc/install?download=go1.10.2.darwin-amd64.pkg#install
And then:
```
mkdir -p $GOPATH/src/github.com/jenkins-x/jx-release-version
git clone git@github.com:jenkins-x/jx-release-version.git $GOPATH/src/github.com/jenkins-x/jx-release-version
cd $GOPATH/src/github.com/jenkins-x/jx-release-version
make
./bin/jx-release-version-darwin --help
```

**Comment by imod** [comment]
I did that already, but as I can not reproduce the issue locally, my problem is making the "hacked" binary available for DEV@Cloud

**Comment by imod** [comment]
yeah!!!! 👍 v1.0.14 fixes the issue 💯 

many thanks!!!

**Comment by rawlingsj** [comment]
@imod YAY!!! Well played!

**Comment by robocoder99** [comment]
Hello, I have this same issue with a private repository on github. I cannot find any documentation on how to handle this situation. When I do a PR it creates the preview environment fine but it does not seem able to perform the promotion to staging. Here are my logs...

```[peerintuit] Running shell script
+ make tag
sed -i -e "s/version:.*/version: failed to get new version error fetching tags: %vexit status 128/" Chart.yaml
sed -i -e "s/repository: .*/repository: 10.23.242.210:5000\/robocoder99\/peerintuit/" values.yaml
sed -i -e "s/tag: .*/tag: failed to get new version error fetching tags: %vexit status 128/" values.yaml
git add --all
git commit -m "release failed to get new version error fetching tags: %vexit status 128" --allow-empty # if first release then no verion update is performed
[master 5cdd155] release failed to get new version error fetching tags: %vexit status 128
 5 files changed, 11 insertions(+), 3 deletions(-)
 create mode 100644 VERSION
 create mode 100644 charts/peerintuit@tmp/durable-0b3a905c/jenkins-log.txt
 create mode 100755 charts/peerintuit@tmp/durable-0b3a905c/script.sh
git tag -fa vfailed to get new version error fetching tags: %vexit status 128 -m "Release version failed to get new version error fetching tags: %vexit status 128"
fatal: too many params
make: *** [tag] Error 128```

**Comment by solderjs** [comment]
I don't even go here, but this is one of the resources I came across when I was trying to figure this out for myself, so I'll share.

I tried EVERY SINGLE POSSIBLE WAY to do this:

- SSH Public Keys
  - SSH_ASKPASS
- API Access Tokens
  - GIT_ASKPASS
  - .gitconfig insteadOf
  - .gitconfig [credential]
  - .git-credentials
  - .netrc
- Bonus: Works with Private Packages
 - node / npm package.json
 - python / pip / eggs requirements.txt
 - ruby gems Gemfile
 - golang go.mod

And this is what I came up with, after much experimentation:

# [The Vanilla DevOps Git Credentials & Private Packages Cheatsheet](https://coolaj86.com/articles/vanilla-devops-git-credentials-cheatsheet/)
